# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_OL_tgeNnWhMxKBPWGXV1MDudTxGg_m_
"""

pip install streamlit scikit-learn pandas numpy

import streamlit as st
from model import predict

st.title("🎓 AI Student Performance Predictor")

st.write("Entrez les informations de l'étudiant")

study_hours = st.slider("Heures d'étude", 0, 10, 5)
attendance = st.slider("Taux de présence (%)", 0, 100, 75)
assignments_score = st.slider("Note des devoirs (/20)", 0, 20, 10)

if st.button("Prédire"):
    result = predict([study_hours, attendance, assignments_score])

    if result == 1:
        st.success("✅ Étudiant en réussite")
    else:
        st.error("⚠️ Étudiant à risque")