# -*- coding: utf-8 -*-
"""modelIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJn-l3TzRHB5Ljzvaj5xNooL890PSRKH
"""

#Import des outils nécessaires
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

#Dataset
np.random.seed(42)

df = pd.DataFrame({
    "study_hours": np.random.randint(0, 10, 200),
    "attendance": np.random.randint(50, 100, 200),
    "assignments_score": np.random.randint(0, 20, 200),
})

#Création de la cible
df["success"] = (
    (df["study_hours"] > 5) &
    (df["attendance"] > 70) &
    (df["assignments_score"] > 10)
).astype(int)

df.head()

#Préparation des données
X = df.drop("success", axis=1)
y = df["success"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Normaliser les données
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Model 1:Regression Logistique
model1 = LogisticRegression()
model1.fit(X_train, y_train)

pred1 = model1.predict(X_test)

print("Logistic Regression Accuracy:", accuracy_score(y_test, pred1))

#Model2:Random Forest
model2 = RandomForestClassifier(n_estimators=100, random_state=42)
model2.fit(X_train, y_train)

pred2 = model2.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, pred2))

#Analyse des Résultats
print("\nClassification Report:\n")
print(classification_report(y_test, pred2))

#Visualisation des données
sns.heatmap(df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation entre variables")
plt.show()

#Ajout d'un système de risque
df["risk"] = (model2.predict(X) == 0).astype(int)

df.head()